/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/junctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all junctions */
        get: operations["listJunctions"];
        put?: never;
        /** Create a new junction configuration */
        post: operations["createJunction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/junctions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get junction details and configuration */
        get: operations["getJunction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensor-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest vehicle detection sensor events */
        post: operations["ingestSensorEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/junctions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get live junction status */
        get: operations["getJunctionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/junctions/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue manual or administrative control command */
        post: operations["issueCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/controller-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest physical or simulated traffic controller responses */
        post: operations["ingestControllerEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/device-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report device status changes (sensor or controller online/offline) */
        post: operations["reportDeviceStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/junctions/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query junction audit history */
        get: operations["getJunctionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/junctions/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream live junction state via Server-Sent Events (SSE) */
        get: operations["streamJunctionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulator/{id}/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set simulator behavior mode for demo/testing */
        post: operations["setSimulatorMode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Direction: "NORTH" | "SOUTH" | "EAST" | "WEST";
        /** @enum {string} */
        Phase: "NS" | "EW";
        /** @enum {string} */
        Signal: "RED" | "YELLOW" | "GREEN" | "UNKNOWN";
        /** @enum {string} */
        Mode: "AUTOMATIC" | "MANUAL" | "EMERGENCY" | "DEGRADED";
        /** @enum {string} */
        VehicleType: "EMERGENCY" | "TRUCK" | "FORKLIFT" | "EMPLOYEE_VEHICLE";
        /** @enum {string} */
        Step: "BOOT" | "GREEN" | "YELLOW" | "ALL_RED";
        /** @enum {string} */
        SimulatorMode: "AUTO_ACK" | "DELAYED" | "SILENT" | "OFFLINE";
        ErrorDetail: {
            /** @example JUNCTION_DEGRADED */
            code: string;
            /** @example Junction controller is offline; commands rejected. */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        JunctionSummary: {
            /** @example A */
            id: string;
            /** @example Main Assembly Crossing */
            name: string;
        };
        CreateJunctionRequest: {
            /** @example A */
            id: string;
            /** @example Main Assembly Crossing */
            name: string;
            /**
             * @example {
             *       "NS": [
             *         "NORTH",
             *         "SOUTH"
             *       ],
             *       "EW": [
             *         "EAST",
             *         "WEST"
             *       ]
             *     }
             */
            phases: {
                [key: string]: components["schemas"]["Direction"][];
            };
            timings?: {
                /** @default 30 */
                green: number;
                /** @default 5 */
                yellow: number;
                /** @default 2 */
                all_red: number;
                /** @default 10 */
                min_green: number;
                /** @default 60 */
                max_green: number;
                /** @default 3 */
                ack_timeout: number;
                /** @default 2 */
                max_retries: number;
                /** @default 90 */
                starvation_after: number;
                /** @default 120 */
                emergency_timeout: number;
                /** @default 300 */
                manual_lease: number;
                /** @default 300 */
                stale_event_after: number;
            };
        };
        JunctionDetail: {
            id: string;
            name: string;
            config: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
        };
        SensorEventRequest: {
            /** @example evt-10001 */
            event_id: string;
            /** @example A */
            junction_id: string;
            direction: components["schemas"]["Direction"];
            /**
             * @example VEHICLE_ARRIVED
             * @enum {string}
             */
            event_type: "VEHICLE_ARRIVED" | "VEHICLE_CLEARED";
            /** @example VH-501 */
            vehicle_id: string;
            vehicle_type?: components["schemas"]["VehicleType"];
            /** @example 1501 */
            sequence_no: number;
            /**
             * Format: date-time
             * @example 2026-10-05T10:15:20Z
             */
            timestamp: string;
        };
        SensorEventResponse: {
            event_id: string;
            /** @enum {string} */
            status: "APPLIED" | "DUPLICATE" | "NOT_APPLIED";
            /** @default false */
            duplicate: boolean;
            reason?: string | null;
        };
        JunctionStatusResponse: {
            /** @example A */
            junction_id: string;
            mode: components["schemas"]["Mode"];
            /** @example NORTH_SOUTH */
            phase: string;
            /** @example ONLINE */
            controller_status: string;
            desired_signals: {
                [key: string]: components["schemas"]["Signal"];
            };
            actual_signals: {
                [key: string]: components["schemas"]["Signal"];
            };
            queues: {
                [key: string]: number;
            };
            transition: {
                step: components["schemas"]["Step"];
                target: string | null;
                deadline_at: number | null;
            };
            pending_commands: string[];
            emergency: {
                active: boolean;
                direction: string | null;
                vehicle_id: string | null;
            };
            manual: {
                active: boolean;
                lease_expires_at: number | null;
                issued_by: string | null;
            };
            alerts: ("CONTROLLER_OFFLINE" | "SIGNAL_FAILURE" | "SENSOR_FAILURE" | "STATE_MISMATCH" | "COMMAND_TIMEOUT" | "UNKNOWN_DEVICE_STATE")[];
            device_statuses: {
                [key: string]: Record<string, never>;
            };
            stale_queues: components["schemas"]["Direction"][];
        };
        AdminCommandRequest: {
            /**
             * @example MANUAL_GREEN_REQUEST
             * @enum {string}
             */
            command: "MANUAL_GREEN_REQUEST" | "RETURN_TO_AUTOMATIC";
            direction?: components["schemas"]["Direction"];
            /** @example admin-1 */
            issued_by?: string;
        };
        AdminCommandResponse: {
            /** @example ACCEPTED */
            status: string;
            message: string;
        };
        ControllerEventRequest: {
            /** @example cmd-8001 */
            command_id: string;
            /** @example A */
            junction_id: string;
            direction?: components["schemas"]["Direction"];
            /**
             * @example ACK
             * @enum {string}
             */
            status: "ACK" | "NACK";
            /** @example GREEN */
            actual_state?: components["schemas"]["Signal"];
            reason?: string | null;
        };
        ControllerEventResponse: {
            command_id: string;
            /** @example PROCESSED */
            status: string;
            /** @default false */
            duplicate: boolean;
        };
        DeviceStatusRequest: {
            /** @example status-301 */
            event_id: string;
            /** @example A */
            junction_id: string;
            /**
             * @example SIGNAL_CONTROLLER
             * @enum {string}
             */
            device_type: "SIGNAL_CONTROLLER" | "SENSOR";
            direction?: components["schemas"]["Direction"];
            /**
             * @example OFFLINE
             * @enum {string}
             */
            status: "ONLINE" | "OFFLINE" | "DEGRADED" | "WARNING" | "UNKNOWN";
            /**
             * Format: date-time
             * @example 2026-10-05T10:30:00Z
             */
            timestamp: string;
        };
        DeviceStatusResponse: {
            event_id: string;
            /** @example UPDATED */
            status: string;
        };
        AuditLogEntry: {
            id: number;
            junction_id: string;
            event_type: string;
            direction?: string | null;
            previous_state?: string | null;
            new_state?: string | null;
            command_id?: string | null;
            reason?: string | null;
            payload?: Record<string, never>;
            /** Format: date-time */
            occurred_at: string;
            source?: string;
        };
        SetSimulatorModeRequest: {
            mode: components["schemas"]["SimulatorMode"];
        };
        SetSimulatorModeResponse: {
            junction_id: string;
            mode: components["schemas"]["SimulatorMode"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listJunctions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of junctions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JunctionSummary"][];
                };
            };
        };
    };
    createJunction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJunctionRequest"];
            };
        };
        responses: {
            /** @description Junction created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JunctionDetail"];
                };
            };
            /** @description Junction already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid junction configuration (e.g., overlapping phases) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Junction details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JunctionDetail"];
                };
            };
            /** @description Junction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingestSensorEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorEventRequest"];
            };
        };
        responses: {
            /** @description Duplicate event ignored idempotently */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorEventResponse"];
                };
            };
            /** @description Sensor event applied to queue/traffic state */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorEventResponse"];
                };
            };
            /** @description Event recorded but not applied (e.g. stale or orphan clear) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorEventResponse"];
                };
            };
            /** @description Unknown junction */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed event or unknown vehicle type */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJunctionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current live junction status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JunctionStatusResponse"];
                };
            };
            /** @description Junction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    issueCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCommandRequest"];
            };
        };
        responses: {
            /** @description Command accepted and queued for transition */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCommandResponse"];
                };
            };
            /** @description Junction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command conflict (e.g. junction DEGRADED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid command parameters */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingestControllerEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControllerEventRequest"];
            };
        };
        responses: {
            /** @description Controller acknowledgement processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControllerEventResponse"];
                };
            };
            /** @description Unknown command_id or junction */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed controller event */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reportDeviceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceStatusRequest"];
            };
        };
        responses: {
            /** @description Device status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceStatusResponse"];
                };
            };
            /** @description Unknown junction */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed device status event */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJunctionHistory: {
        parameters: {
            query?: {
                limit?: number;
                before_id?: number;
                event_type?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated audit history records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogEntry"][];
                };
            };
            /** @description Junction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    streamJunctionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Real-time event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Junction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setSimulatorMode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSimulatorModeRequest"];
            };
        };
        responses: {
            /** @description Simulator mode updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetSimulatorModeResponse"];
                };
            };
            /** @description Junction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid mode */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
